version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8008:80
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: to_do
      POSTGRES_HOST: 127.0.0.1
    ports:
      - 5432:5432
