"""'init'

Revision ID: 6e64cbb73e2f
Revises: 96dbb572c96a
Create Date: 2021-12-15 11:16:20.942251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e64cbb73e2f'
down_revision = '96dbb572c96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
